name: Customer workflow - run_attempt
on:
  workflow_dispatch
  
jobs:
  new-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo test
  new-job2:
    runs-on: ubuntu-latest
    needs: new-job
    steps:
      - run: |
          date
          echo ${{ github.run_attempt }}
  new-job3:
    runs-on: ubuntu-latest
    needs: new-job2
    steps:
      - run: |
          non-existing-bad-command
