name: Testing run_attempt
on:
  workflow_dispatch
  
jobs:
  new-job:
    runs-on: ubuntu-latest
    #needs: test-job
    steps:
      - run: |
          echo ${{ github.run_attempt }}
      - run: | 
          non-existing-bad-command
          
