name: No concurrency
on:
  workflow_dispatch
  
jobs:
  new-job:
    runs-on: ubuntu-latest
    #needs: test-job
    steps:
      - run: |
          echo ${{ github.run_attempt }}
      - run: | 
          echo Testing
          bbbbb
          
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo ${{ github.run_attempt }}
          
          
