name: Concurrency test
on:
  push

concurrency:
  group: group: ${{ github.ref_name == 'main' && github.run_id || join([github.workflow,github.ref]) }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          sleep 30
          echo ${{ github.ref_name == 'main' && github.run_id || join([github.workflow,github.ref]) }}
          echo ${{ github.ref_name != 'main' }}
     
