name: Concurrency test
on:
  push

concurrency:
  group: ${{ github.ref_name == 'master' && github.run_id || github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'master' }}
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          sleep 60
          echo ${{ github.ref_name == 'master' && github.run_id || github.ref }}
          echo ${{ github.ref_name != 'master' }}
     
