name: Concurrency test
on:
  push

concurrency:
  group: ${{ github.ref_name == 'main' && github.run_id || github.workflow }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          sleep 60
          echo ${{ github.ref_name }}
          echo ${{ github.ref_name == 'main' && github.run_id || github.ref }}
          echo ${{ github.ref_name != 'main' }}
     
