name: Concurrency test
on:
  push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          sleep 60
          echo ${{ !contains(github.ref, 'main/')}}
          echo ${{ github.workflow }}-${{ github.ref }}
     
