name: Concurrency test
on:
  push

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          sleep 30
          echo ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
     
