name: Concurrency test
on:
  push

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          sleep 30
          echo ${{ github.ref_name }}
          echo ${{ github.ref_name != 'main' }}
     
