name: Queue jobs
on:
  workflow_dispatch

concurrency:
  group: ${{ github.run_id }}
  cancel-in-progress: false
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          sleep 30
          echo ${{ github.run_id }}
